analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:2143169,"name"\:"SkylineX","teamId"\:2123168,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:200326,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:2123168,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
